require 'test/test_combination'
require 'test/test_fundamental'
require 'test/test_matrix'
require 'test/test_polynomial'
require 'test/test_prime'
require 'test/test_rational'
require 'test/test_sequence'
require 'test/test_vector'
